# ports: HOST:CONTAINER
version: '3.8'
services:
    python:
        build: .
        container_name: xray-proxy-grabber-telegram-python
        restart: unless-stopped
        environment:
            - PYTHONUNBUFFERED=1
#        network_mode: host
        volumes:
            - ./v2ray-proxy-grabber-telegram.session:/v2ray-proxy-grabber-telegram.session

